version: '2'
services:
  webapp:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    entrypoint: ["sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
    ports:
      - "8080:8080"
    links:
      - mysql
      - redis
  
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: logins 
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  